#!/usr/bin/env node

/**
 * Figma CLI Daemon
 *
 * Supports two modes:
 * - Yolo Mode (CDP): Direct connection via Chrome DevTools Protocol (fast, requires patching)
 * - Safe Mode (Plugin): Connection via Figma plugin WebSocket (secure, no patching)
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - The /plugin WebSocket upgrade checks token + Origin (lib/daemon-auth.js)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, statSync, writeFileSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { homedir, tmpdir } from 'os';
import { fileURLToPath, pathToFileURL } from 'url';
import { wrapCodeIfNeeded } from './lib/eval-wrap.js';
import { validateHttpRequest, validateUpgrade } from './lib/daemon-auth.js';

// Hot-reload FigmaClient: copy to temp file and import (Node.js ES modules don't support cache busting)
const __dirname = dirname(fileURLToPath(import.meta.url));
const figmaClientPath = join(__dirname, 'figma-client.js');
let FigmaClient = null;
let lastModTime = 0;
let lastTempFile = null;

// Serialised: two concurrent requests used to both pass the mtime test, and the second's
// cleanup unlinked the file the first was importing (ERR_MODULE_NOT_FOUND, then a fall back to
// the STALE module). One reload at a time; the copy is named with its pid as well, so a
// second daemon on another port cannot delete this one's copy.
let reloading = null;
async function getFigmaClient() {
  if (reloading) await reloading;
  let stat;
  try { stat = statSync(figmaClientPath); } catch { stat = null; }
  const modTime = stat ? stat.mtimeMs : 0;
  if (FigmaClient && modTime <= lastModTime) return FigmaClient;

  reloading = (async () => {
    try {
      const tempFile = join(__dirname, `.figma-client-${modTime}.${process.pid}.mjs`);
      // Drop OUR earlier copy only — never a file another process may be importing.
      if (lastTempFile && lastTempFile !== tempFile) { try { unlinkSync(lastTempFile); } catch {} }
      // Copy next to the original so its relative imports resolve
      writeFileSync(tempFile, readFileSync(figmaClientPath, 'utf8'));
      lastTempFile = tempFile;
      const module = await import(pathToFileURL(tempFile).href);
      FigmaClient = module.FigmaClient;
      const wasReload = lastModTime > 0;
      lastModTime = modTime;
      if (wasReload) {
        console.log('[daemon] Hot-reloaded figma-client.js');
        // The cached CDP client is an instance of the OLD class; drop it so the next
        // request builds one from the reloaded module.
        if (cdpClient) { try { cdpClient.close(); } catch {} cdpClient = null; }
      }
    } catch (e) {
      // A read-only install (global npm) cannot take the copy; import the module once
      // and stop trying — every request used to log this error and retry the write.
      if (!FigmaClient) {
        console.error('[daemon] Hot-reload unavailable (' + e.message + '); loading figma-client.js once');
        FigmaClient = (await import('./figma-client.js')).FigmaClient;
      }
      lastModTime = Number.MAX_SAFE_INTEGER;
    } finally {
      reloading = null;
    }
  })();
  await reloading;
  return FigmaClient;
}

/** Remove this daemon's hot-reload copy (called on shutdown). */
function removeHotReloadCopy() {
  if (lastTempFile) { try { unlinkSync(lastTempFile); } catch {} lastTempFile = null; }
}

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const MODE = process.env.DAEMON_MODE || 'auto'; // 'auto', 'cdp', 'plugin'
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // Default: 60 minutes (long interactive design sessions have quiet stretches; the CLI also auto-restarts the daemon if it ever does shut down)

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.figma-ds-cli', '.daemon-token');
// This daemon owns the singleton PID file ONLY once it wins the port bind (see
// httpServer.listen below). The CLI no longer writes it, so the file always
// points at the daemon actually serving on the port — never a crashed loser.
const PID_FILE = join(homedir(), '.figma-cli-daemon.pid');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all requests.');
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Host header (blocks DNS rebinding) + session token (blocks other local
  // processes). The rules live in lib/daemon-auth.js, shared with the
  // WebSocket upgrade below, and are unit-tested there.
  return validateHttpRequest(req.headers, SESSION_TOKEN);
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer()

// CDP Client (Yolo Mode)
let cdpClient = null;
let isCdpConnecting = false;
let lastHealthCheck = 0;
let lastHealthResult = false;
const HEALTH_CACHE_MS = 30000; // Cache health for 30 seconds (reduces overhead)

// Plugin Client (Safe Mode)
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

// ============ CDP MODE (YOLO) ============

async function isCdpHealthy(forceCheck = false) {
  // Quick WebSocket state check (no network call)
  if (!cdpClient || !cdpClient.ws) return false;
  if (cdpClient.ws.readyState !== 1) return false;

  // Use cached result if recent (avoids constant eval calls)
  const now = Date.now();
  if (!forceCheck && now - lastHealthCheck < HEALTH_CACHE_MS) {
    return lastHealthResult;
  }

  try {
    const result = await Promise.race([
      cdpClient.eval('1'), // Simple eval, just check connection works
      new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 2000))
    ]);
    lastHealthCheck = now;
    lastHealthResult = result === 1;
    return lastHealthResult;
  } catch {
    lastHealthCheck = now;
    lastHealthResult = false;
    return false;
  }
}

async function getCdpClient() {
  // Fast path: if we have a client with open WebSocket, use it
  if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
    return cdpClient;
  }

  // WebSocket closed, need to reconnect
  if (cdpClient) {
    console.log('[daemon] CDP WebSocket closed, reconnecting...');
    try { cdpClient.close(); } catch {}
    cdpClient = null;
    lastHealthResult = false;
  }

  // Wait if another connection attempt is in progress
  if (isCdpConnecting) {
    while (isCdpConnecting) {
      await new Promise(r => setTimeout(r, 100));
    }
    // The other attempt may have failed and left cdpClient null —
    // fall through and try connecting ourselves instead of returning null.
    if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
      return cdpClient;
    }
  }

  isCdpConnecting = true;
  try {
    const ClientClass = await getFigmaClient();
    cdpClient = new ClientClass();
    // FIGMA_FILE pins the daemon to a specific open file (substring match on the
    // tab title). Without it Figma's first design tab wins, which silently sends
    // commands to the wrong file when several are open.
    await cdpClient.connect(process.env.FIGMA_FILE || null);
    lastHealthCheck = Date.now();
    lastHealthResult = true;
    console.log('[daemon] Connected to Figma via CDP (Yolo Mode)');
  } finally {
    isCdpConnecting = false;
  }
  return cdpClient;
}

async function evalViaCdp(code) {
  const client = await getCdpClient();
  return client.eval(code);
}

// ============ PLUGIN MODE (SAFE) ============

function isPluginConnected() {
  return pluginWs && pluginWs.readyState === WebSocket.OPEN;
}

// One budget per request, from the CLI (`--timeout`, default 90 s), used by the daemon and
// forwarded to the plugin. Four unrelated numbers used to live here (25 s plugin-side, 25 s
// daemon-side, 60 s per batch, 90 s in the CLI): a 5-item Safe Mode batch timed out on the
// daemon while the plugin kept building, and the late result was dropped.
const DEFAULT_TIMEOUT_MS = 90000;

async function evalViaPlugin(code, retryCount = 0, timeoutMs = DEFAULT_TIMEOUT_MS) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the Figma CLI Bridge plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin execution timeout (${timeoutMs / 1000}s)`));
    }, timeoutMs);

    pluginPendingRequests.set(id, { resolve, reject, timeout, code, retryCount });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval',
        id: id,
        code: code,
        timeoutMs: timeoutMs
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// Batch eval via plugin (execute multiple codes, return all results)
async function evalBatchViaPlugin(codes, timeoutMs = DEFAULT_TIMEOUT_MS) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the Figma CLI Bridge plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    // The plugin runs the items one after another, each within `timeoutMs`; the daemon
    // waits for the whole batch.
    const budget = timeoutMs * codes.length;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin batch execution timeout (${budget / 1000}s for ${codes.length} items)`));
    }, budget);

    pluginPendingRequests.set(id, { resolve, reject, timeout, isBatch: true });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval-batch',
        id: id,
        codes: codes,
        timeoutMs: timeoutMs
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin batch send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============


async function executeEval(code, timeoutMs = DEFAULT_TIMEOUT_MS) {
  // Auto mode: prefer plugin if connected, fallback to CDP
  if (MODE === 'auto') {
    if (isPluginConnected()) {
      // Plugin handles its own wrapping, send code as-is
      return evalViaPlugin(code, 0, timeoutMs);
    }
    // CDP needs wrapping for top-level return statements
    return evalViaCdp(wrapCodeIfNeeded(code));
  }

  // Explicit mode
  if (MODE === 'plugin') {
    // Plugin handles its own wrapping
    return evalViaPlugin(code, 0, timeoutMs);
  }

  // CDP mode
  return evalViaCdp(wrapCodeIfNeeded(code));
}

function getMode() {
  if (MODE === 'plugin') return 'safe';
  if (MODE === 'cdp') return 'yolo';
  // Auto: return what's actually connected
  if (isPluginConnected()) return 'safe';
  if (cdpClient) return 'yolo';
  return 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // SECURITY: No CORS headers (blocks all cross-origin browser requests)

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Only an authenticated request counts as activity — before, a stream of 403s from any
  // local process kept the daemon alive forever.
  resetIdleTimer();

  // Health check
  if (req.url === '/health') {
    const mode = getMode();
    const pluginConnected = isPluginConnected();
    const cdpHealthy = await isCdpHealthy();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: (pluginConnected || cdpHealthy) ? 'ok' : 'disconnected',
      mode: mode,
      plugin: pluginConnected,
      cdp: cdpHealthy,
      // Which open file this daemon is bound to. The CLI compares it against
      // FIGMA_FILE and rebinds when they diverge — otherwise commands silently
      // hit whichever file happened to be first when the daemon started.
      file: (cdpClient && cdpClient.pageTitle) || null,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Force reconnect (CDP only)
  if (req.url === '/reconnect') {
    try {
      if (cdpClient) {
        try { cdpClient.close(); } catch {}
        cdpClient = null;
      }
      await getCdpClient();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'reconnected', mode: 'yolo' }));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    // utf8 via setEncoding: a StringDecoder keeps a multi-byte character whole across chunk
    // boundaries (`body += chunk` decoded each Buffer on its own, so an umlaut on a 64 KB
    // boundary turned into U+FFFD inside the file). Capped, and with an error listener so an
    // aborted upload cannot raise an unhandled 'error' on the request.
    const MAX_BODY_BYTES = 64 * 1024 * 1024;
    let body = '';
    let received = 0;
    let tooLarge = false;
    req.setEncoding('utf8');
    req.on('error', (e) => console.error('[daemon] request error:', e.message));
    req.on('data', chunk => {
      received += Buffer.byteLength(chunk);
      if (received > MAX_BODY_BYTES) {
        if (!tooLarge) {
          tooLarge = true;
          res.writeHead(413, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: `Request body over ${MAX_BODY_BYTES / 1024 / 1024} MB` }));
          req.destroy();
        }
        return;
      }
      body += chunk;
    });
    req.on('end', async () => {
      if (tooLarge) return;
      const MAX_RETRIES = 2;
      let lastError;

      // Parse once, outside the retry loop — a malformed body never becomes
      // valid by retrying, and retries used to tear down a healthy CDP
      // connection for it.
      let payload;
      try {
        payload = JSON.parse(body);
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
        return;
      }

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray, gap, vertical, collection, autoStyle } = payload;
          // One budget for daemon and plugin, from the CLI's --timeout (default 90 s).
          const timeoutMs = Number(payload.timeoutMs) > 0 ? Number(payload.timeoutMs) : DEFAULT_TIMEOUT_MS;
          let result;

          const execWithTimeout = async (fn, timeoutMs = DEFAULT_TIMEOUT_MS) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error(`Execution timeout (${timeoutMs/1000}s)`)), timeoutMs)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code, timeoutMs), timeoutMs);
              break;
            case 'render': {
              // Parse JSX to code, then execute via unified eval (works with both CDP and Plugin)
              const ClientClass = await getFigmaClient();
              const parser = new ClientClass();
              // The same two knobs render-batch honours below; --collection was silently
              // ignored on this path.
              if (collection) parser.setCollection(collection);
              if (autoStyle === false) parser.setAutoTextStyle(false);
              const renderCode = await parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode, timeoutMs), timeoutMs);
              break;
            }
            case 'render-batch': {
              // Single eval for ALL frames (10x faster than loop)
              const ClientClass = await getFigmaClient();
              const batchParser = new ClientClass();
              if (collection) batchParser.setCollection(collection);
              if (autoStyle === false) batchParser.setAutoTextStyle(false);
              const batchCode = await batchParser.parseJSXBatch(jsxArray, {
                gap: gap || 40,
                vertical: vertical || false
              });
              result = await execWithTimeout(() => executeEval(batchCode, timeoutMs), timeoutMs);
              break;
            }
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result, mode: getMode() }));
          return;
        } catch (error) {
          lastError = error;
          console.log(`[daemon] Attempt ${attempt + 1} failed: ${error.message}`);

          // NEVER retry a mutating render: executeEval may have already created
          // the frame before the response errored (a transient CDP hiccup under
          // load, e.g. several heavy files open). Retrying re-runs the render
          // code and silently produces a DUPLICATE frame. Fail fast instead —
          // a clear error beats a phantom copy. (Reads/eval may still retry.)
          if (payload.action === 'render' || payload.action === 'render-batch') break;

          // For Safe Mode: wait briefly for potential reconnect
          if (attempt < MAX_RETRIES && MODE === 'plugin') {
            console.log('[daemon] Safe Mode: waiting for plugin reconnect...');
            // Wait up to 2s for plugin to reconnect
            for (let i = 0; i < 10; i++) {
              await new Promise(r => setTimeout(r, 200));
              if (isPluginConnected()) {
                console.log('[daemon] Plugin reconnected, retrying...');
                break;
              }
            }
          }

          // For Yolo Mode: only reconnect when the connection is actually
          // broken. If CDP is healthy, the error came from the executed code
          // itself — retrying would just re-run it (and a timed-out render
          // would create duplicate nodes).
          if (attempt < MAX_RETRIES && MODE !== 'plugin' && !isPluginConnected()) {
            if (await isCdpHealthy(true)) {
              console.log('[daemon] CDP healthy — error is not connection-related, not retrying');
              break;
            }
            console.log('[daemon] Reconnecting CDP before retry...');
            // Don't tear down a connection another request is currently building
            if (!isCdpConnecting) {
              try { if (cdpClient) cdpClient.close(); } catch {}
              cdpClient = null;
            }
            // Backoff: 300ms after first failure, 1s after second
            await new Promise(r => setTimeout(r, attempt === 0 ? 300 : 1000));
            try {
              await getCdpClient();
              if (!(await isCdpHealthy(true))) {
                console.log('[daemon] CDP still unhealthy after reconnect');
              }
            } catch (reconnectError) {
              console.log('[daemon] CDP reconnect failed: ' + reconnectError.message);
            }
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: (lastError && lastError.message) || 'Execution failed' }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections.
// `noServer`: the upgrade is accepted by hand so that the same auth as HTTP
// runs first. Attached to the server directly, ws would complete the
// handshake for anyone — and a WebSocket from a web page needs no CORS
// preflight, so any open tab could have become "the plugin" and read every
// eval the CLI sent.
const wss = new WebSocketServer({ noServer: true });

httpServer.on('upgrade', (req, socket, head) => {
  const authError = validateUpgrade(req, SESSION_TOKEN);
  if (authError) {
    console.error('[daemon] Plugin upgrade rejected: ' + authError);
    socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');
    socket.destroy();
    return;
  }
  wss.handleUpgrade(req, socket, head, (ws) => wss.emit('connection', ws, req));
});

wss.on('connection', (ws) => {
  console.log('[daemon] Plugin connected (Safe Mode)');
  // A reopened plugin tab replaces the old socket; close the old one so its late 'close'
  // cannot be mistaken for ours (see the identity check in the close handler).
  if (pluginWs && pluginWs !== ws) { try { pluginWs.close(); } catch {} }
  pluginWs = ws;
  resetIdleTimer(); // Plugin connection counts as activity

  ws.on('message', (data) => {
    resetIdleTimer(); // Plugin messages count as activity
    try {
      const msg = JSON.parse(data.toString());

      if (msg.type === 'hello') {
        console.log(`[daemon] Plugin version: ${msg.version}`);
      }

      if (msg.type === 'result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);

          if (msg.error) {
            pending.reject(new Error(msg.error));
          } else {
            pending.resolve(msg.result);
          }
        }
      }

      // Batch result from plugin
      if (msg.type === 'batch-result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);
          pending.resolve(msg.results);
        }
      }

      // Keepalive ping from plugin
      if (msg.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong' }));
      }

      if (msg.type === 'pong') {
        // Health check response
      }
    } catch (e) {
      console.error('[daemon] Plugin message error:', e);
    }
  });

  ws.on('close', () => {
    // Only the live socket's close means "plugin gone": the handler used to null `pluginWs`
    // for ANY socket, so an old tab's delayed close killed the new tab's connection.
    if (pluginWs !== ws) return;
    console.log('[daemon] Plugin disconnected');
    pluginWs = null;

    // Reject all pending requests
    for (const [id, pending] of pluginPendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Plugin disconnected'));
    }
    pluginPendingRequests.clear();
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

// Singleton guard: a second daemon spawned by a concurrent CLI invocation
// (startDaemon has a check-then-act race) will fail to bind the port. Exit it
// cleanly BEFORE it does any work, and do NOT let it touch the PID file — so the
// winner stays the one true daemon. Without this the loser used to crash on an
// unhandled 'error' while the CLI had already written ITS pid to the PID file,
// so isDaemonRunning() saw a dead pid and respawned endlessly (daemon churn →
// non-deterministic double execution).
httpServer.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    console.log(`[daemon] Port ${PORT} already owned by another daemon — exiting (singleton).`);
    process.exit(0);
  }
  console.error('[daemon] server error:', err);
  process.exit(1);
});

httpServer.listen(PORT, '127.0.0.1', () => {
  // We won the bind: claim the singleton PID file.
  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  console.log(`[daemon] Figma CLI daemon running on port ${PORT} (pid ${process.pid})`);
  console.log(`[daemon] Mode: ${MODE === 'auto' ? 'auto (plugin preferred, CDP fallback)' : MODE}`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  removeHotReloadCopy();
  if (cdpClient) cdpClient.close();
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}

// In auto/cdp mode, pre-connect to Figma
if (MODE !== 'plugin') {
  getCdpClient().catch(err => {
    console.log('[daemon] CDP not available, waiting for plugin connection...');
  });
}
