#!/usr/bin/env node

/**
 * Figma CLI Daemon
 *
 * Supports three modes:
 * - Pipe Mode (CDP over --remote-debugging-pipe): the daemon launches Figma and holds its
 *   debugging pipe — no patch, no port. Default on macOS/Linux since 2026-09-11.
 * - Yolo Mode (CDP over the port): direct connection via Chrome DevTools Protocol (requires
 *   the app.asar patch, or Browser Mode)
 * - Safe Mode (Plugin): Connection via Figma plugin WebSocket (secure, no patching)
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - The /plugin WebSocket upgrade checks token + Origin (lib/daemon-auth.js)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, statSync, writeFileSync, unlinkSync, readdirSync, openSync } from 'fs';
import { join, dirname } from 'path';
import { homedir, tmpdir } from 'os';
import { fileURLToPath, pathToFileURL } from 'url';
import { spawn } from 'child_process';
import { wrapCodeIfNeeded } from './lib/eval-wrap.js';
import { validateHttpRequest, validateUpgrade } from './lib/daemon-auth.js';
import { spawnFigmaWithPipe, inheritedPipe, successorEnv, designTargets, reloadTarget } from './lib/figma-pipe.js';
import { getFigmaBinaryPath, getCdpPort } from './figma-patch.js';
import { staleClientCopies, processExists } from './lib/hot-reload-copies.js';
import { probeCdpClient, serveCachedHealth } from './lib/cdp-health.js';
import { retryVerdict, failureLine } from './lib/exec-retry.js';

// Hot-reload FigmaClient: copy to temp file and import (Node.js ES modules don't support cache busting)
const __dirname = dirname(fileURLToPath(import.meta.url));
const figmaClientPath = join(__dirname, 'figma-client.js');
// Same file the CLI's startDaemon points a fresh daemon at (src/lib/cli-core.js).
const DAEMON_LOG_FILE = join(homedir(), '.figma-ds-cli', 'daemon.log');
let FigmaClient = null;
let lastModTime = 0;
let lastTempFile = null;

// Serialised: two concurrent requests used to both pass the mtime test, and the second's
// cleanup unlinked the file the first was importing (ERR_MODULE_NOT_FOUND, then a fall back to
// the STALE module). One reload at a time; the copy is named with its pid as well, so a
// second daemon on another port cannot delete this one's copy.
let reloading = null;
async function getFigmaClient() {
  if (reloading) await reloading;
  let stat;
  try { stat = statSync(figmaClientPath); } catch { stat = null; }
  const modTime = stat ? stat.mtimeMs : 0;
  if (FigmaClient && modTime <= lastModTime) return FigmaClient;

  reloading = (async () => {
    try {
      const tempFile = join(__dirname, `.figma-client-${modTime}.${process.pid}.mjs`);
      // Drop OUR earlier copy only — never a file another process may be importing.
      if (lastTempFile && lastTempFile !== tempFile) { try { unlinkSync(lastTempFile); } catch {} }
      // Copy next to the original so its relative imports resolve
      writeFileSync(tempFile, readFileSync(figmaClientPath, 'utf8'));
      lastTempFile = tempFile;
      const module = await import(pathToFileURL(tempFile).href);
      FigmaClient = module.FigmaClient;
      const wasReload = lastModTime > 0;
      lastModTime = modTime;
      if (wasReload) {
        console.log('[daemon] Hot-reloaded figma-client.js');
        // The cached CDP client is an instance of the OLD class; drop it so the next
        // request builds one from the reloaded module.
        if (cdpClient) { try { cdpClient.close(); } catch {} cdpClient = null; }
      }
    } catch (e) {
      // A read-only install (global npm) cannot take the copy; import the module once
      // and stop trying — every request used to log this error and retry the write.
      if (!FigmaClient) {
        console.error('[daemon] Hot-reload unavailable (' + e.message + '); loading figma-client.js once');
        FigmaClient = (await import('./figma-client.js')).FigmaClient;
      }
      lastModTime = Number.MAX_SAFE_INTEGER;
    } finally {
      reloading = null;
    }
  })();
  await reloading;
  return FigmaClient;
}

/** Remove this daemon's hot-reload copy (called on shutdown). */
function removeHotReloadCopy() {
  if (lastTempFile) { try { unlinkSync(lastTempFile); } catch {} lastTempFile = null; }
}

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const MODE = process.env.DAEMON_MODE || 'auto'; // 'auto', 'cdp', 'plugin', 'pipe'
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // Default: 60 minutes (long interactive design sessions have quiet stretches; the CLI also auto-restarts the daemon if it ever does shut down)

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.figma-ds-cli', '.daemon-token');
// This daemon owns the singleton PID file ONLY once it wins the port bind (see
// httpServer.listen below). The CLI no longer writes it, so the file always
// points at the daemon actually serving on the port — never a crashed loser.
const PID_FILE = join(homedir(), '.figma-cli-daemon.pid');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all requests.');
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Host header (blocks DNS rebinding) + session token (blocks other local
  // processes). The rules live in lib/daemon-auth.js, shared with the
  // WebSocket upgrade below, and are unit-tested there.
  return validateHttpRequest(req.headers, SESSION_TOKEN);
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  // Pipe Mode: this process holds Figma's debugging pipe, and Figma may quit when it goes.
  // It lives as long as Figma does; the pipe closing is what ends it.
  if (MODE === 'pipe') return;
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer()

// CDP Client (Yolo Mode)
let cdpClient = null;
let isCdpConnecting = false;
let lastHealthCheck = 0;
let lastHealthResult = false;

// Figma's debugging pipe (Pipe Mode): { transport, toBrowser, fromBrowser, child? }
let pipe = null;
// Why the last pipe connect attempt failed, null once attached. Reported in /health so the panel
// can say "no loaded file — click its tab" instead of "connecting…" forever.
let pipeError = null;
let handingOff = false;

// Plugin Client (Safe Mode)
let pluginWs = null;
let pluginFile = null; // name of the file the connected plugin runs in (from its hello)
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

// ============ CDP MODE (YOLO) ============

async function isCdpHealthy(forceCheck = false) {
  // Quick WebSocket state check (no network call)
  if (!cdpClient || !cdpClient.ws) return false;
  if (cdpClient.ws.readyState !== 1) return false;

  // Cached while it is worth caching. A positive keeps for half a minute; a negative only for
  // one panel poll, because the probe also fails on a Figma that is merely busy — a 21 s render
  // used to leave every command saying "Not connected" for the next 30 seconds
  // (src/lib/cdp-health.js).
  const now = Date.now();
  if (!forceCheck && serveCachedHealth(lastHealthResult, now - lastHealthCheck)) {
    return lastHealthResult;
  }

  // Asks for `figma`, not for `1`: `1` evaluates in any context, so a Figma that dropped its
  // plugin realm mid-session still read as Connected while every command failed. A client whose
  // context lost `figma` is released here, so the next request (and the pipe loop) attach anew
  // instead of evaluating into a realm without the Plugin API. See src/lib/cdp-health.js.
  const verdict = await probeCdpClient(cdpClient, { timeoutMs: 2000 });
  lastHealthCheck = now;
  lastHealthResult = verdict === 'healthy';
  if (verdict === 'no-figma' && !isCdpConnecting) {
    console.log('[daemon] `figma` is gone from the bound execution context — dropping the client to re-attach');
    try { cdpClient.close(); } catch {}
    cdpClient = null;
  }
  return lastHealthResult;
}

async function getCdpClient() {
  // Fast path: if we have a client with open WebSocket, use it
  if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
    return cdpClient;
  }

  // WebSocket closed, need to reconnect
  if (cdpClient) {
    console.log('[daemon] CDP WebSocket closed, reconnecting...');
    try { cdpClient.close(); } catch {}
    cdpClient = null;
    lastHealthResult = false;
  }

  // Wait if another connection attempt is in progress
  if (isCdpConnecting) {
    while (isCdpConnecting) {
      await new Promise(r => setTimeout(r, 100));
    }
    // The other attempt may have failed and left cdpClient null —
    // fall through and try connecting ourselves instead of returning null.
    if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
      return cdpClient;
    }
  }

  isCdpConnecting = true;
  try {
    const ClientClass = await getFigmaClient();
    // Connect on a LOCAL client and publish it only once it is fully connected — with its
    // execution context found. cdpClient used to be assigned before connect resolved, so
    // during the ~500 ms context scan cdpClient.ws was already open; isCdpHealthy (which
    // evals `1`, valid in any context) reported healthy, /health went green, and an eval
    // arriving in that window ran in the default context where `figma` is undefined.
    const client = new ClientClass();
    // FIGMA_FILE pins the daemon to a specific open file (substring match on the
    // tab title). Without it Figma's first design tab wins, which silently sends
    // commands to the wrong file when several are open.
    if (MODE === 'pipe') {
      if (!pipe || pipe.transport.closed) throw new Error('Figma pipe is not open — run figma-cli connect');
      await client.connectViaPipe(pipe.transport, process.env.FIGMA_FILE || null);
    } else {
      await client.connect(process.env.FIGMA_FILE || null);
    }
    cdpClient = client;
    lastHealthCheck = Date.now();
    lastHealthResult = true;
    console.log(`[daemon] Connected to Figma via CDP (${MODE === 'pipe' ? 'Pipe' : 'Yolo'} Mode)`);
  } finally {
    isCdpConnecting = false;
  }
  return cdpClient;
}

async function evalViaCdp(code) {
  const client = await getCdpClient();
  return client.eval(code);
}

// ============ PLUGIN MODE (SAFE) ============

function isPluginConnected() {
  return pluginWs && pluginWs.readyState === WebSocket.OPEN;
}

// One budget per request, from the CLI (`--timeout`, default 90 s), used by the daemon and
// forwarded to the plugin. Four unrelated numbers used to live here (25 s plugin-side, 25 s
// daemon-side, 60 s per batch, 90 s in the CLI): a 5-item Safe Mode batch timed out on the
// daemon while the plugin kept building, and the late result was dropped.
const DEFAULT_TIMEOUT_MS = 90000;

async function evalViaPlugin(code, retryCount = 0, timeoutMs = DEFAULT_TIMEOUT_MS) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Run the FigCli plugin in Figma (Plugins → Development → FigCli).');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin execution timeout (${timeoutMs / 1000}s)`));
    }, timeoutMs);

    pluginPendingRequests.set(id, { resolve, reject, timeout, code, retryCount });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval',
        id: id,
        code: code,
        timeoutMs: timeoutMs
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============


async function executeEval(code, timeoutMs = DEFAULT_TIMEOUT_MS) {
  // Auto mode: prefer plugin if connected, fallback to CDP
  if (MODE === 'auto') {
    if (isPluginConnected()) {
      // Plugin handles its own wrapping, send code as-is
      return evalViaPlugin(code, 0, timeoutMs);
    }
    // CDP needs wrapping for top-level return statements
    return evalViaCdp(wrapCodeIfNeeded(code));
  }

  // Explicit mode
  if (MODE === 'plugin') {
    // Plugin handles its own wrapping
    return evalViaPlugin(code, 0, timeoutMs);
  }

  // CDP mode
  return evalViaCdp(wrapCodeIfNeeded(code));
}

/** A small JSON body (1 MB cap); null when empty or malformed. /exec has its own 64 MB reader. */
function readJsonBody(req, limit = 1024 * 1024) {
  return new Promise((resolve) => {
    let raw = '';
    req.on('data', (chunk) => { raw += chunk; if (raw.length > limit) { raw = ''; req.destroy(); } });
    req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : null); } catch { resolve(null); } });
    req.on('error', () => resolve(null));
  });
}

function getMode() {
  if (MODE === 'pipe') return 'pipe';
  if (MODE === 'plugin') return 'safe';
  if (MODE === 'cdp') return 'yolo';
  // Auto: return what's actually connected
  if (isPluginConnected()) return 'safe';
  if (cdpClient) return 'yolo';
  return 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // SECURITY: No CORS headers (blocks all cross-origin browser requests)

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Only an authenticated request counts as activity — before, a stream of 403s from any
  // local process kept the daemon alive forever.
  resetIdleTimer();

  // Health check
  // `/health/force` skips the cache. Pipe and Safe Mode have no debug port, so a command there
  // has no second opinion to fall back on — it asks this route once before it declares the
  // connection lost (src/lib/connection-gate.js).
  if (req.url === '/health' || req.url === '/health/force') {
    const mode = getMode();
    const pluginConnected = isPluginConnected();
    const cdpHealthy = await isCdpHealthy(req.url === '/health/force');

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: (pluginConnected || cdpHealthy) ? 'ok' : 'disconnected',
      mode: mode,
      plugin: pluginConnected,
      cdp: cdpHealthy,
      // Pipe Mode: this daemon holds Figma's debugging pipe. `cdp` says whether a file is
      // attached; `pipe` says Figma is ours even while it is still loading.
      pipe: MODE === 'pipe' && !!pipe && !pipe.transport.closed,
      // Pipe Mode, not attached: why the last attempt failed (the loop keeps trying). null when
      // attached or before the first attempt has failed.
      pipeError: MODE === 'pipe' && !cdpHealthy ? pipeError : null,
      // Which open file this daemon is bound to. The CLI compares it against
      // FIGMA_FILE and rebinds when they diverge — otherwise commands silently
      // hit whichever file happened to be first when the daemon started.
      file: (cdpClient && cdpClient.pageTitle) || pluginFile || null,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // The open design files, as `/json` on the port lists them. Pipe Mode has no port, so the
  // CLI's `files`, bin/fig-status and the panel ask here.
  if (req.url === '/files') {
    try {
      let files;
      if (MODE === 'pipe') {
        if (!pipe || pipe.transport.closed) throw new Error('Figma pipe is not open');
        const ClientClass = await getFigmaClient();
        files = await ClientClass.listPagesViaPipe(pipe.transport);
      } else {
        const answer = await fetch(`http://127.0.0.1:${getCdpPort()}/json`, { signal: AbortSignal.timeout(2000) });
        files = (await answer.json())
          .filter((p) => p.url && /figma\.com\/(design|file|board)\//.test(p.url))
          .map((p) => ({ title: p.title, id: p.id, url: p.url }));
      }
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(files));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Hand Figma's pipe to a fresh daemon process and step down. `daemon restart` in Pipe Mode:
  // a plain stop-and-start would drop the pipe, and Figma may quit with it. The successor gets
  // the two pipe sockets as its fds 3 and 4 (Node duplicates a stream's descriptor into the
  // child), waits for this process to release the port, and carries on with the same Figma.
  if (req.url === '/handoff' && req.method === 'POST') {
    if (MODE !== 'pipe' || !pipe || pipe.transport.closed) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Not in Pipe Mode, or the pipe is closed' }));
      return;
    }
    // `daemon restart` sends the pin it runs under (`{file}`); the successor must start with it,
    // or the panel's "Bind file" — which is exactly a pinned restart — lost the pin in the handoff.
    const handoffBody = await readJsonBody(req);
    const pinnedFile = handoffBody && typeof handoffBody.file === 'string' ? handoffBody.file : '';
    let successor;
    // The successor opens the log itself (append) rather than inheriting this process's
    // stdout: a daemon that predates the log file has none to hand down, and every later
    // handoff would inherit that nothing — the panel's restart never produced a log.
    let logFd = 'ignore';
    try { logFd = openSync(DAEMON_LOG_FILE, 'a'); } catch {}
    try {
      successor = spawn(process.execPath, [fileURLToPath(import.meta.url)], {
        detached: true,
        stdio: ['ignore', logFd, logFd, pipe.toBrowser, pipe.fromBrowser],
        env: successorEnv(process.env, pinnedFile),
      });
      successor.unref();
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: `Could not spawn the successor: ${error.message}` }));
      return;
    }
    handingOff = true;
    console.log(`[daemon] Handing the pipe to daemon pid ${successor.pid}`);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ status: 'handing-off', pid: successor.pid }));
    // Let the answer leave, then free the port for the successor. shutdown() leaves the pipe
    // alone while handingOff is set; our copies of the descriptors close with the process,
    // the successor's duplicates keep Figma's pipe open.
    setTimeout(shutdown, 200);
    return;
  }

  // Force reconnect. POST {"file": "…"} rebinds to another open file without a restart —
  // the only way to rebind in Pipe Mode, where a restart means handing over the pipe.
  // With "reload": true (the panel's Reconnect), a failed attach in Pipe Mode reloads the bound
  // file's tab and waits for `figma` — what closing and reopening the file did by hand.
  if (req.url === '/reconnect') {
    let reload = false;
    try {
      if (req.method === 'POST') {
        const body = await readJsonBody(req);
        if (body && typeof body.file === 'string') process.env.FIGMA_FILE = body.file;
        reload = !!(body && body.reload);
      }
      if (cdpClient) {
        try { cdpClient.close(); } catch {}
        cdpClient = null;
      }
      let reloaded = false;
      try {
        await getCdpClient();
      } catch (error) {
        if (!(reload && MODE === 'pipe')) throw error;
        await reloadBoundTab(error);
        reloaded = true;
      }
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'reconnected', mode: getMode(), file: cdpClient && cdpClient.pageTitle || null, reloaded }));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    // utf8 via setEncoding: a StringDecoder keeps a multi-byte character whole across chunk
    // boundaries (`body += chunk` decoded each Buffer on its own, so an umlaut on a 64 KB
    // boundary turned into U+FFFD inside the file). Capped, and with an error listener so an
    // aborted upload cannot raise an unhandled 'error' on the request.
    const MAX_BODY_BYTES = 64 * 1024 * 1024;
    let body = '';
    let received = 0;
    let tooLarge = false;
    req.setEncoding('utf8');
    req.on('error', (e) => console.error('[daemon] request error:', e.message));
    req.on('data', chunk => {
      received += Buffer.byteLength(chunk);
      if (received > MAX_BODY_BYTES) {
        if (!tooLarge) {
          tooLarge = true;
          // Stop reading, answer, and only then tear the socket down. `req.destroy()` straight
          // after `res.end()` destroys the socket the answer still rides on: the client then got
          // ECONNRESET instead of the 413, which is a thrown `fetch` rather than a status. It
          // depended on load — the full suite saw it three times, the test file alone never.
          req.pause();
          res.writeHead(413, { 'Content-Type': 'application/json', Connection: 'close' });
          res.end(JSON.stringify({ error: `Request body over ${MAX_BODY_BYTES / 1024 / 1024} MB` }),
            () => req.destroy());
        }
        return;
      }
      body += chunk;
    });
    req.on('end', async () => {
      if (tooLarge) return;
      const MAX_RETRIES = 2;
      let lastError;

      // Parse once, outside the retry loop — a malformed body never becomes
      // valid by retrying, and retries used to tear down a healthy CDP
      // connection for it.
      let payload;
      try {
        payload = JSON.parse(body);
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
        return;
      }

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray, gap, vertical, collection, autoStyle } = payload;
          // One budget for daemon and plugin, from the CLI's --timeout (default 90 s).
          const timeoutMs = Number(payload.timeoutMs) > 0 ? Number(payload.timeoutMs) : DEFAULT_TIMEOUT_MS;
          let result;

          const execWithTimeout = async (fn, timeoutMs = DEFAULT_TIMEOUT_MS) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error(`Execution timeout (${timeoutMs/1000}s)`)), timeoutMs)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code, timeoutMs), timeoutMs);
              break;
            case 'render': {
              // Parse JSX to code, then execute via unified eval (works with both CDP and Plugin)
              const ClientClass = await getFigmaClient();
              const parser = new ClientClass();
              // The same two knobs render-batch honours below; --collection was silently
              // ignored on this path.
              if (collection) parser.setCollection(collection);
              if (autoStyle === false) parser.setAutoTextStyle(false);
              const renderCode = await parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode, timeoutMs), timeoutMs);
              break;
            }
            case 'render-batch': {
              // Single eval for ALL frames (10x faster than loop)
              const ClientClass = await getFigmaClient();
              const batchParser = new ClientClass();
              if (collection) batchParser.setCollection(collection);
              if (autoStyle === false) batchParser.setAutoTextStyle(false);
              const batchCode = await batchParser.parseJSXBatch(jsxArray, {
                gap: gap || 40,
                vertical: vertical || false
              });
              result = await execWithTimeout(() => executeEval(batchCode, timeoutMs), timeoutMs);
              break;
            }
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result, mode: getMode() }));
          return;
        } catch (error) {
          lastError = error;
          console.log(failureLine(attempt, error));

          // Two things are never run twice, whatever the health probe says (src/lib/exec-retry.js):
          // a mutating render — executeEval may have created the frame before the answer
          // failed, and a second run is a duplicate frame — and an error Figma itself raised,
          // because then the code ran up to the throw and a second run repeats every mutation
          // before it. Only a transport fault may reconnect and try again.
          const verdict = retryVerdict({ action: payload.action, attempt, maxRetries: MAX_RETRIES, error });
          if (verdict === 'mutating') break;
          if (verdict === 'from-figma') {
            console.log('[daemon] Raised inside Figma — the code ran, not retrying');
            break;
          }

          // For Safe Mode: wait briefly for potential reconnect
          if (attempt < MAX_RETRIES && MODE === 'plugin') {
            console.log('[daemon] Safe Mode: waiting for plugin reconnect...');
            // Wait up to 2s for plugin to reconnect
            for (let i = 0; i < 10; i++) {
              await new Promise(r => setTimeout(r, 200));
              if (isPluginConnected()) {
                console.log('[daemon] Plugin reconnected, retrying...');
                break;
              }
            }
          }

          // For Yolo Mode: only reconnect when the connection is actually
          // broken. If CDP is healthy, the error came from the executed code
          // itself — retrying would just re-run it (and a timed-out render
          // would create duplicate nodes).
          if (attempt < MAX_RETRIES && MODE !== 'plugin' && !isPluginConnected()) {
            if (await isCdpHealthy(true)) {
              console.log('[daemon] CDP healthy — error is not connection-related, not retrying');
              break;
            }
            console.log('[daemon] Reconnecting CDP before retry...');
            // Don't tear down a connection another request is currently building
            if (!isCdpConnecting) {
              try { if (cdpClient) cdpClient.close(); } catch {}
              cdpClient = null;
            }
            // Backoff: 300ms after first failure, 1s after second
            await new Promise(r => setTimeout(r, attempt === 0 ? 300 : 1000));
            try {
              await getCdpClient();
              if (!(await isCdpHealthy(true))) {
                console.log('[daemon] CDP still unhealthy after reconnect');
              }
            } catch (reconnectError) {
              console.log('[daemon] CDP reconnect failed: ' + reconnectError.message);
            }
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: (lastError && lastError.message) || 'Execution failed' }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections.
// `noServer`: the upgrade is accepted by hand so that the same auth as HTTP
// runs first. Attached to the server directly, ws would complete the
// handshake for anyone — and a WebSocket from a web page needs no CORS
// preflight, so any open tab could have become "the plugin" and read every
// eval the CLI sent.
const wss = new WebSocketServer({ noServer: true });

httpServer.on('upgrade', (req, socket, head) => {
  const authError = validateUpgrade(req, SESSION_TOKEN);
  if (authError) {
    console.error('[daemon] Plugin upgrade rejected: ' + authError);
    socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');
    socket.destroy();
    return;
  }
  wss.handleUpgrade(req, socket, head, (ws) => wss.emit('connection', ws, req));
});

wss.on('connection', (ws) => {
  console.log('[daemon] Plugin connected (Safe Mode)');
  // A reopened plugin tab replaces the old socket; close the old one so its late 'close'
  // cannot be mistaken for ours (see the identity check in the close handler).
  if (pluginWs && pluginWs !== ws) { try { pluginWs.close(); } catch {} }
  pluginWs = ws;
  resetIdleTimer(); // Plugin connection counts as activity

  ws.on('message', (data) => {
    resetIdleTimer(); // Plugin messages count as activity
    try {
      const msg = JSON.parse(data.toString());

      if (msg.type === 'hello') {
        // The file the plugin runs in. /health used to know a file only from the CDP page
        // title, so in Safe Mode it said null and FIGMA_FILE pinning never compared anything.
        pluginFile = typeof msg.file === 'string' && msg.file ? msg.file : null;
      }

      if (msg.type === 'result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);

          if (msg.error) {
            pending.reject(new Error(msg.error));
          } else {
            pending.resolve(msg.result);
          }
        }
      }

      // Keepalive ping from plugin
      if (msg.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong' }));
      }

      if (msg.type === 'pong') {
        // Health check response
      }
    } catch (e) {
      console.error('[daemon] Plugin message error:', e);
    }
  });

  ws.on('close', () => {
    // Only the live socket's close means "plugin gone": the handler used to null `pluginWs`
    // for ANY socket, so an old tab's delayed close killed the new tab's connection.
    if (pluginWs !== ws) return;
    console.log('[daemon] Plugin disconnected');
    pluginWs = null;
    pluginFile = null;

    // Reject all pending requests
    for (const [id, pending] of pluginPendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Plugin disconnected'));
    }
    pluginPendingRequests.clear();
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

// Singleton guard: a second daemon spawned by a concurrent CLI invocation
// (startDaemon has a check-then-act race) will fail to bind the port. Exit it
// cleanly BEFORE it does any work, and do NOT let it touch the PID file — so the
// winner stays the one true daemon. Without this the loser used to crash on an
// unhandled 'error' while the CLI had already written ITS pid to the PID file,
// so isDaemonRunning() saw a dead pid and respawned endlessly (daemon churn →
// non-deterministic double execution).
let bindAttempts = 0;
httpServer.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    // A handed-over daemon starts while its predecessor is still closing the port.
    if (process.env.FIGMA_PIPE_INHERIT === '1' && bindAttempts++ < 25) {
      setTimeout(() => httpServer.listen(PORT, '127.0.0.1'), 200);
      return;
    }
    console.log(`[daemon] Port ${PORT} already owned by another daemon — exiting (singleton).`);
    process.exit(0);
  }
  console.error('[daemon] server error:', err);
  process.exit(1);
});

// Hot-reload copies whose daemon died without `shutdown()` (killed, crashed, taken down with
// Figma's pipe) stay in src/ forever; only the owning pid can import a copy, so a copy of a
// dead pid is garbage. Swept once per start, after the bind, so a losing singleton never runs it.
function sweepStaleHotReloadCopies() {
  let names;
  try { names = readdirSync(__dirname); } catch { return; }
  for (const name of staleClientCopies(names, processExists)) {
    try { unlinkSync(join(__dirname, name)); } catch {}
  }
}

httpServer.listen(PORT, '127.0.0.1', () => {
  // We won the bind: claim the singleton PID file.
  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  sweepStaleHotReloadCopies();
  console.log(`[daemon] Figma CLI daemon running on port ${PORT} (pid ${process.pid})`);
  console.log(`[daemon] Mode: ${MODE === 'auto' ? 'auto (plugin preferred, CDP fallback)' : MODE}`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  removeHotReloadCopy();
  if (cdpClient && !handingOff) cdpClient.close();
  if (pipe && !handingOff) pipe.transport.close();
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  // Node 18: close() stops accepting but keeps serving open keep-alive sockets (fetch keeps
  // one), so a shut-down daemon answered for another 3 s until the force exit. Node 19+ does
  // this inside close(); on 18 it is a separate call.
  if (typeof httpServer.closeIdleConnections === 'function') httpServer.closeIdleConnections();
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}

// ============ PIPE MODE (default on macOS/Linux) ============

function openPipe() {
  if (process.env.FIGMA_PIPE_INHERIT === '1') {
    pipe = inheritedPipe();
    console.log('[daemon] Took over Figma\'s debugging pipe from the previous daemon');
  } else if (process.env.FIGMA_PIPE_LAUNCH === '1') {
    const binary = process.env.FIGMA_BINARY || getFigmaBinaryPath();
    const launched = spawnFigmaWithPipe(binary);
    pipe = launched;
    console.log(`[daemon] Launched Figma with --remote-debugging-pipe (pid ${launched.child.pid})`);
    launched.child.on('exit', (code, signal) => console.log(`[daemon] Figma exited (${code ?? signal})`));
  } else {
    // A daemon respawned by the CLI after Figma quit must not launch Figma on its own — that
    // would open Figma from a random `figma-cli` command. `connect` sets FIGMA_PIPE_LAUNCH.
    console.error('[daemon] Pipe Mode needs a Figma to hold: run figma-cli connect');
    process.exit(2);
  }
  pipe.transport.on('close', () => {
    if (handingOff) return;
    console.log('[daemon] Figma\'s debugging pipe closed — shutting down');
    shutdown();
  });
  pipe.transport.on('error', (e) => console.error('[daemon] pipe error:', e.message));
}

// Figma loads its file for ~20 s after launch; until a design page and the `figma` context
// exist, connectViaPipe throws. Keep trying in the background so /health turns green on its
// own — the CLI's `connect` polls /health and never sends work before that.
async function pipeConnectLoop() {
  while (pipe && !pipe.transport.closed && !handingOff) {
    if (!(cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1)) {
      try {
        await getCdpClient();
        pipeError = null;
      } catch (error) {
        // Logged when it changes, not every two seconds: the reason is what matters ("no loaded
        // design file among 2 open tabs"), and it used to be swallowed entirely.
        const message = error && error.message ? error.message : String(error);
        if (message !== pipeError) console.log(`[daemon] Pipe: not attached — ${message}`);
        pipeError = message;
      }
    } else {
      pipeError = null;
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
}

// Reconnect's last resort in Pipe Mode: the attach found the tab but no `figma` in it — Figma
// dropped its plugin realm, or the tab was restored without loading. Reload that one tab over the
// pipe (Page.reload on its own session) and attach again as soon as `figma` is back. Measured
// 18 Sep on a throwaway file: ~9 s, Figma's PID unchanged, no dialog; while the page loads its
// title is briefly gone, so "not open" answers during the wait are expected and retried.
const RELOAD_WAIT_MS = 30000;
async function reloadBoundTab(attachError) {
  if (!pipe || pipe.transport.closed) throw attachError;
  const transport = pipe.transport;
  const answer = await transport.send('Target.getTargets', {}, undefined, { timeoutMs: 5000 });
  if (answer.error) throw attachError;
  const plan = reloadTarget(designTargets(answer.result?.targetInfos), process.env.FIGMA_FILE || '');
  if (!plan.target) throw new Error(`${attachError.message} — not reloaded: ${plan.reason}`);
  const attached = await transport.send('Target.attachToTarget', { targetId: plan.target.id, flatten: true }, undefined, { timeoutMs: 5000 });
  const sessionId = attached.result?.sessionId;
  if (attached.error || !sessionId) throw new Error(`${attachError.message} — reload failed: ${attached.error?.message || 'no session'}`);
  try {
    const reloaded = await transport.send('Page.reload', {}, sessionId, { timeoutMs: 5000 });
    if (reloaded.error) throw new Error(`${attachError.message} — reload failed: ${reloaded.error.message}`);
  } finally {
    transport.send('Target.detachFromTarget', { sessionId }, undefined, { timeoutMs: 2000 }).catch(() => {});
  }
  console.log(`[daemon] Reconnect: reloaded "${plan.target.title}", waiting for figma`);
  const deadline = Date.now() + RELOAD_WAIT_MS;
  let last = attachError;
  while (Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 2000));
    if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) return; // the background loop won
    try { await getCdpClient(); return; } catch (error) { last = error; }
  }
  throw new Error(`Reloaded "${plan.target.title}", but figma did not come back within ${RELOAD_WAIT_MS / 1000} s: ${last.message}`);
}

if (MODE === 'pipe') {
  openPipe();
  pipeConnectLoop();
} else if (MODE !== 'plugin') {
  // In auto/cdp mode, pre-connect to Figma
  getCdpClient().catch(err => {
    console.log('[daemon] CDP not available, waiting for plugin connection...');
  });
}
